### ISSUE TITLE
Plugin crashes on test run

### ISSUE THREAD

**Issue by jmtimko5** [NeuraLegion/cypress-har-generator#173] opened 2023-01-19 23:02 UTC
**Description**
I installed according the readme, ran my first test with `cy.recordHar()` in the `before` hook. I got the following error

```
Error
Your configFile threw an error from: cypress.config.js

We stopped running your tests because your config file crashed.

[Stack trace](http://localhost:53986/__launchpad/index.html#)
Error: Session with given id not found.
    at /Users/josephtimko/work/netspring/firewatch/node_modules/chrome-remote-interface/lib/chrome.js:94:35
    at Chrome._handleMessage (/Users/josephtimko/work/netspring/firewatch/node_modules/chrome-remote-interface/lib/chrome.js:257:17)
    at WebSocket. (/Users/josephtimko/work/netspring/firewatch/node_modules/chrome-remote-interface/lib/chrome.js:235:22)
    at WebSocket.emit (events.js:400:28)
    at WebSocket.emit (domain.js:475:12)
    at Receiver.receiverOnMessage (/Users/josephtimko/work/netspring/firewatch/node_modules/chrome-remote-interface/node_modules/ws/lib/websocket.js:1068:20)
    at Receiver.emit (events.js:400:28)
    at Receiver.emit (domain.js:475:12)
    at Receiver.dataMessage (/Users/josephtimko/work/netspring/firewatch/node_modules/chrome-remote-interface/node_modules/ws/lib/receiver.js:517:14)
    at /Users/josephtimko/work/netspring/firewatch/node_modules/chrome-remote-interface/node_modules/ws/lib/receiver.js:468:23
    at /Users/josephtimko/work/netspring/firewatch/node_modules/chrome-remote-interface/node_modules/ws/lib/permessage-deflate.js:308:9
    at /Users/josephtimko/work/netspring/firewatch/node_modules/chrome-remote-interface/node_modules/ws/lib/permessage-deflate.js:391:7
    at afterWrite (internal/streams/writable.js:466:5)
    at onwrite (internal/streams/writable.js:446:7)
    at InflateRaw.afterTransform (internal/streams/transform.js:103:3)
    at Zlib.processCallback (zlib.js:607:8)
```
**Steps to reproduce**
Cypress Version: 10.10
Here is my cypress.config.ts
```
import { defineConfig } from "cypress";
import del from "del";
import { install } from "@neuralegion/cypress-har-generator";

import { dataSeedingRoutine } from "./cypress/helpers/seeding-utils";

/* eslint-disable no-console */

export default defineConfig({
	// env: {
	// 	hars_folders: "cypress/hars",
	// },
	e2e: {
		specPattern: "cypress/integration/**/*.spec.(js|ts)",
		viewportWidth: 1792,
		viewportHeight: 1024,
		defaultCommandTimeout: 10000,
		videoUploadOnPasses: false,
		animationDistanceThreshold: 2,
		retries: {
			runMode: 1,
			openMode: 0,
		},
		projectId: "fzgkok",
		experimentalInteractiveRunEvents: true,
		async setupNodeEvents(on, config) {
			require("@cypress/code-coverage/task")(on, config);
			console.log("install");
			console.log(install);
			// console.log("hey now");
			on("before:run", async (details) => {
				// We do not run this in CI because this runs N times where N is the number of parallel machines executing cypress tests
				// This has been extracted to a step before the cypress test step to ensure it only runs once.
				if (config.env.isLocal) {
					dataSeedingRoutine(config);
				}
			});
			// @ts-ignore
			on("after:spec", (spec, results) => {
				if (results?.stats?.failures === 0 && results?.video) {
					// `del()` returns a promise, so it's important to return it to ensure
					// deleting the video is finished before moving on
					return del(results.video);
				}
			});
			await install(on);
		},
	},
});
```

**Comment by derevnjuk** [comment] 2023-01-20 12:10
@jmtimko5 thank you for submitting your report. Can you please provide additional details such as the browser you are using, how your test looks like, and any other relevant information?

**Comment by derevnjuk** [comment] 2023-01-31 18:45
@jmtimko5 I'm unable to reproduce the issue without further information. I'll enhance error handling and include debug messages for improved troubleshooting. Closing the issue.

**Comment by jmtimko5** [comment] 2023-01-31 19:10
@derevnjuk My apologies for the delay. The browser I am using is Chrome, and the test fails immediately on the cy.visit command. Is there any other information I can provide? Please reopen the issue when you get a chance

**Comment by derevnjuk** [comment] 2023-01-31 19:21
@jmtimko5 thanks for the response 😉  Could you attach an output obtained by running tests with the `NODE_DEBUG=cypress-har-generator` environment variable? 

```bash
$ NODE_DEBUG=cypress-har-generator cypress run --browser chrome
```

Please first upgrade the plugin to the latest version: https://github.com/NeuraLegion/cypress-har-generator/releases/tag/v5.14.1

**Comment by jmtimko5** [comment] 2023-02-04 02:43
Hi there. I used the latest version as you stated, but the error is unfortunately seemingly empty
```
GET /_next/static/chunks/styles.js?ts=1675478556492 200 102.541 ms - -
GET /_next/static/chunks/main.js?ts=1675478556492 200 78.469 ms - -
CYPRESS-HAR-GENERATOR 48397: Failed request: 48945.165. Reason: net::ERR_ABORTED
CYPRESS-HAR-GENERATOR 48397: Failed request: 48945.175. Reason: net::ERR_ABORTED
🍑 Unable to attach to target. Please open an issue on the repository: https://github.com/NeuraLegion/cypress-har-generator/issues for assistance.

The stack trace for this error is:
GET /_next/static/chunks/1.js 200 514.511 ms - -
```

**Comment by derevnjuk** [comment] 2023-02-06 08:54
@jmtimko5 Sorry, this information is not sufficient. Let's try some tricks to gather more information to identify the root cause.
1. Place the file at the root directory under the following path (i.e. `./patches/chrome-remote-interface+0.31.3.patch`):

```
diff --git a/node_modules/chrome-remote-interface/lib/chrome.js b/node_modules/chrome-remote-interface/lib/chrome.js
index fb97a70..b02cd38 100644
--- a/node_modules/chrome-remote-interface/lib/chrome.js
+++ b/node_modules/chrome-remote-interface/lib/chrome.js
@@ -4,6 +4,7 @@ const EventEmitter = require('events');
 const util = require('util');
 const formatUrl = require('url').format;
 const parseUrl = require('url').parse;
+const debuglog = require('util').debuglog;
 
 const WebSocket = require('ws');
 
@@ -11,6 +12,8 @@ const api = require('./api.js');
 const defaults = require('./defaults.js');
 const devtools = require('./devtools.js');
 
+const log = debuglog('cypress-har-generator');
+
 class ProtocolError extends Error {
     constructor(request, response) {
         let {message} = response;
@@ -245,6 +248,7 @@ class Chrome extends EventEmitter {
 
     // handle the messages read from the WebSocket
     _handleMessage(message) {
+        log('The plugin receives from the CDP: %j', message);
         // command response
         if (message.id) {
             const callback = this._callbacks[message.id];
@@ -283,6 +287,7 @@ class Chrome extends EventEmitter {
             sessionId,
             params: params || {}
         };
+        log('The plugin sends to the CDP: %j', message);
         this._ws.send(JSON.stringify(message), (err) => {
             if (err) {
                 // handle low-level WebSocket errors

```
2. Apply the patch using this command:

```bash
$ npx patch-package  
```
3. Re-run your tests as before, and now you should observe the following logs in the output:
```
CYPRESS-HAR-GENERATOR 74572: send: {"id":5,"method":"Network.enable","sessionId":"B0E6A6C649DA8A23B7DC27DF32E83AC1","params":{}}
```
4. Attach the output to the ticket.

**Comment by derevnjuk** [comment] 2023-02-14 06:47
@jmtimko5, can you provide an update?

**Comment by jmtimko5** [comment] 2023-02-14 17:08
Hi @derevnjuk, I am currently in a extremely busy time at work. I will need a bit of time to run this test. I appreciate your patience.

**Comment by you1anna** [comment] 2023-03-06 19:04
Hi @derevnjuk I'm also experiencing this issue.

Cypress v12.7
Chrome v110

I'm using the suggested setup on the readme and getting the same error as @jmtimko5. 

Here is the log output from `$NODE_DEBUG=cypress-har-generator cypress run --browser chrome`

[debug.log](https://github.com/NeuraLegion/cypress-har-generator/files/10901952/debug.log)

**Comment by derevnjuk** [comment] 2023-03-07 05:57
@you1anna, thank you for submitting the report. After reviewing the provided logs, I did not detect any errors or crashes. It appears that your tests have passed without any issues. However, I noticed that the logs lack the most crucial part. Have you forwarded all the outputs to the file like this `NODE_DEBUG=cypress-har-generator cypress run --browser chrome > allout.txt 2>&1`? Additionally, if possible, could you reduce the scope enabling only the single test that is causing the issue?

**Comment by you1anna** [comment] 2023-03-07 09:49
@derevnjuk It only seems to fail like this when run in headed/UI mode. The tests run and pass on the console.

If I run `NODE_DEBUG=cypress-har-generator yarn cy:run:smoke --browser chrome > allout.txt 2>&1` the command returns without doing anything. Is it ok to include the `yarn` command? Anything else I could try?

**Comment by derevnjuk** [comment] 2023-03-07 10:01
@jmtimko5, it's fine. It will redirect all outputs (standard output and standard error) to `allout.txt` file located in the working directory. Just attach this file here if you still experience this issue.

**Comment by you1anna** [comment] 2023-03-07 11:35
Hi @derevnjuk, this is the smallest test I have - please see attached outputs. Hope it helps.

[outputad.txt](https://github.com/NeuraLegion/cypress-har-generator/files/10908866/outputad.txt)
[outputac.txt](https://github.com/NeuraLegion/cypress-har-generator/files/10908869/outputac.txt)
[outputab.txt](https://github.com/NeuraLegion/cypress-har-generator/files/10908871/outputab.txt)
[outputaa.txt](https://github.com/NeuraLegion/cypress-har-generator/files/10908873/outputaa.txt)

**Comment by you1anna** [comment] 2023-03-08 07:50
We are seeing a few issues between Chrome v109 and v110, may be related?

**Comment by you1anna** [comment] 2023-03-13 11:36
Hi @derevnjuk do we have an eta of when a fix may be available for this? We are eager to add this to our project, thanks.

**Comment by derevnjuk** [comment] 2023-03-13 11:52
@you1anna seems you are not experiencing the same issue since the logs you have provided do not show any errors or issues, either related to the reported problem or any other errors. Additionally, your tests have been completed successfully as I can see. Would it be possible for you to kindly provide a reproducible repository for further investigation?

**Comment by you1anna** [comment] 2023-03-14 11:50
@derevnjuk it only seems to be an issue when running in UI mode. I'm sorry I don't have time to make a repo for this.

Please can you confirm if my config is valid? 

`const { defineConfig } = require('cypress')
const path = require('path');

const queryTestDb = require( './db');

const {downloadFile} = require('cypress-downloadfile/lib/addPlugin')

const {
  install,
  ensureBrowserFlags
} = require('@neuralegion/cypress-har-generator');


module.exports = defineConfig({
    pageLoadTimeout: 80000,
    requestTimeout: 120000,
    defaultCommandTimeout: 120000,
    responseTimeout: 80000,
    videoCompression: 25,
    waitForAnimations: true,
    projectId: "5eapb9",
    viewportWidth: 1280,
    viewportHeight: 800,
    video: true,
    videosFolder: "cypress/videos",
    screenshotOnRunFailure: true,
    screenshotsFolder: "cypress/screenshots",
    trashAssetsBeforeRuns: true,
    chromeWebSecurity: false,
    parseSpecialCharSequences: false,
    videoUploadOnPasses: false,
    numTestsKeptInMemory: 10,    
    reporter: "mochawesome",
    retries: {
      runMode: 0,
      openMode: 0
    },
    env: {
      environment: "development",
      db: {
        host: "mysql",
        user: "rguser",
        password: "password",
        database: "rg"
      },
      tenant_db: {
        host: "mysql",
        user: "root",
        password: "password",
        database: "8a98e6b3d06d4c1885d7fc239c87a2c9"
      }
    },
  e2e: {
    baseUrl: "https://site1.xxx.dev",
    setupNodeEvents(on, config) {

      const options = {
        outputRoot: config.projectRoot + '/',
        outputTarget: {
          'terminal-report.log': 'txt'
        }
      };
      require('cypress-terminal-report/src/installLogsPrinter')(on, options);

      install(on);
      on('before:browser:launch', (browser = {}, launchOptions) => {
          ensureBrowserFlags(browser, launchOptions);
          if (browser.name === "chrome") {
            const ignoreXFrameHeadersExtension = path.join(__dirname, '../extensions/ignore-x-frame-headers');
            launchOptions.args.push(launchOptions.args.push(`--load-extension=${ignoreXFrameHeadersExtension}`));
            launchOptions.args.push("--disable-features=CrossSiteDocumentBlockingIfIsolating,CrossSiteDocumentBlockingAlways,IsolateOrigins,site-per-process");
            launchOptions.args.push('--no-sandbox');
            launchOptions.args.push('--disable-gpu');
          }
          return launchOptions
        })
      
        on('task', {
          log(message) {
            console.log(message)
      
            return null
          },
          table(message) {
            console.table(message)
      
            return null
          }
        })
      
        on('task', {
          queryDb: ({query, useTenant}) => {
            return queryTestDb({query, useTenant, config})
          },
        })
        on('task', {downloadFile})
    }
  }
})`

When launching Cypress 12.7 and running a test, I get this:

<img width="982" alt="Screenshot 2023-03-14 at 11 47 30" src="https://user-images.githubusercontent.com/7108767/224991847-95eb19c2-d1bc-447c-b86e-4970920418db.png">

**Closed** 2023-03-14 14:40 UTC
Labels: Type: bug

**Comment by derevnjuk** [comment] 2023-03-14 14:42
@you1anna, your configuration appears to be correct. However, I don't believe that any misconfiguration issues are causing this error. There are a couple of reasons why this error may occur:

* The target may have closed during initialization.
* The target may have crashed due to memory issues.

Despite it is possible to emulate this error, it does not explain the root cause of the issue. Therefore, I have improved the debug messages and adjusted the implementation to prevent tests from crashing due to this error. 

Please install the latest version (i.e. [v5.16.4](https://github.com/NeuraLegion/cypress-har-generator/releases/tag/v5.16.4)) and verify if it works for you. If you encounter a warning stating "Unable to attach to the target," please rerun your tests in debug mode (by setting the `NODE_DEBUG` environment variable to `cypress-har-generator`, e.g. `NODE_DEBUG=cypress-har-generator cypress open --browser chrome` for the interactive mode) and attach the entire output to the ticket for further investigation and improvements.

@jmtimko5 fyi

**Comment by you1anna** [comment] 2023-03-14 17:35
Tests are now running on the latest release, thanks a lot!
